export const SEARCH_QUERY_START = "SEARCH_QUERY_START";
export const SEARCH_QUERY_SUCCESS = "SEARCH_QUERY_SUCCESS";
export const SEARCH_QUERY_FAIL = "SEARCH_QUERY_FAIL";

export const SET_QUERY = "SET_QUERY";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

export const SET_INITIAL_STATE = "SET_INITIAL_STATE";

export const GET_MOVIE_START = "GET_MOVIE_START";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_FAIL = "GET_MOVIE_FAIL";

export const GET_SUGGESTION_START = "GET_SUGGESTION_START";
export const GET_SUGGESTION_SUCCESS = "GET_SUGGESTION_SUCCESS";
export const GET_SUGGESTION_FAIL = "GET_SUGGESTION_FAIL";
export const HIDE_SUGGESTION = "HIDE_SUGGESTION";
export const SHOW_SUGGESTION = "SHOW_SUGGESTION";
export const CLEAR_SUGGESTION = "CLEAR_SUGGESTION";
